Import ('env')

import subprocess as sp
proc = sp.Popen('gcc -dumpversion', shell=True, stdout=sp.PIPE)
version = proc.stdout.read()
version = version.strip()

if version == "4.6":
	env.Append(CXXFLAGS=['-I/usr/lib/gcc/x86_64-linux-gnu/4.6/plugin/include/'])
	deps = ['gcc_plugin_4.6']
else:
	env.Append(CXXFLAGS=['-I/usr/lib/gcc/x86_64-linux-gnu/4.7/plugin/include/'])	
	deps = ['gcc_plugin_4.7']

name = 'namecheck'	
inc = ['../namecheck']
src = ['APIMock.cpp', '../src/BasePlugin.cpp', '../src/RulesContainer.cpp', '../src/NamingConventionPlugin.cpp']
src += ['../src/UpperUnderscoreRule.cpp', '../src/UpperCamelCaseRule.cpp', '../src/LowerUnderscoreRule.cpp', '../src/LowerCamelCaseRule.cpp', '../src/DefaultRules.cpp', '../src/Regex.cpp']
deps += ['gtest_main', 'gmock', 'gtest','boost_regex', 'mili']

env.CreateTest(name, inc, src, deps)